import type { Metadata } from "next";
import { M_PLUS_1 } from "next/font/google";
import "./globals.scss";
import Header from "../components/Header";
import clsx from "clsx";

const mplusone = M_PLUS_1({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`h-lvh w-lvw antialiased grid grid-cols-[420px_1fr] overflow-hidden`}
            >
                <Header />
                <div
                    className={clsx(
                        `${mplusone.className} py-12 px-8 text-accent`,
                        "bg-gradient-to-br from-bg-background to-background-gradient"
                    )}
                >
                    {/* morse */}
                    <div className="absolute flex flex-col w-[4px] gap-3 -translate-x-2/4 -ml-4 opacity-60 [&>*:nth-child(3n)]:mb-6">
                        <span className="dot" />
                        <span className="bar" />
                        <span className="dot" />

                        <span className="dot" />
                        <span className="bar" />
                        <span className="dot" />

                        <span className="bar" />
                        <span className="dot" />
                        <span className="bar" />

                        <span className="dot" />
                        <span className="bar" />
                        <span className="dot" />

                        <span className="bar" />
                        <span className="dot" />
                    </div>

                    {children}
                </div>
            </body>
        </html>
    );
}
